name: Prevarisc-passerelle-platau Lint

on:
  pull_request:
  push:
    branches:
      - master
      - feature/github-Actions
jobs:
  validate-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, dom
          tools: composer
      - name: Installer les dépendances
        run: composer install --prefer-dist --no-progress 
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  psalm:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1 
          extensions: mbstring, xml, dom
      - uses: ramsey/composer-install@v3
      - name: Installer les dépendances
        run: composer install --prefer-dist --no-progress 
      - name: Exécuter Psalm
        run: vendor/bin/psalm

  phpunit:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - uses: ramsey/composer-install@v3
    - name: Installer les dépendances
      run: composer install --prefer-dist --no-progress 
    - name: Exécuter PHPUnit
      run: vendor/bin/phpunit

  php-cs-fixer-rules:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - uses: ramsey/composer-install@v3
    - name: Installer les dépendances
      run: composer install --prefer-dist --no-progress 
    - name: Exécuter PHP CS Fixer
      run: vendor/bin/php-cs-fixer check --diff --config=vendor/kdubuc/php-cs-fixer-rules/php-cs-fixer.php






