name: Prevarisc-passerelle-platau Lint

on:
  pull_request:
  push:
    branches:
      - master
      - feature/github-Actions

jobs:
  validate-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Validate composer.json and composer.lock
        run: 
          composer validate --strict
  
  psalm:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, dom, opcache
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: "--prefer-dist"

      - name: Exécuter Psalm
        run: vendor/bin/psalm
  
  php-cs-fixer:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - uses: ramsey/composer-install@v3
      with:
        composer-options: "--prefer-dist"    
     
    - name: Exécuter PHP CS Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff --config=vendor/kdubuc/php-cs-fixer-rules/php-cs-fixer.php
